print("The integer equivalent of B is", ord('B'))
print("The integer equivalent of C is", ord('C'))
print("The integer equivalent of D is", ord('D'))
print("The integer equivalent of b is", ord('b'))
print("The integer equivalent of c is", ord('c'))
print("The integer equivalent of d is", ord('d'))
print("The integer equivalent of 0 is", ord('0'))
print("The integer equivalent of 1 is", ord('1'))
print("The integer equivalent of 2 is", ord('2'))
print("The integer equivalent of $ is", ord('$'))
print("The integer equivalent of * is", ord('*'))
print("The integer equivalent of + is", ord('+'))
print("The integer equivalent of blank space is", ord(' '))
